#  Buổi 3

names=[...]: Đặt tên cho các cột vì file gốc không có header

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [14]:
from email.quoprimime import header_check

price = df["price"]

In [15]:
type(price)

pandas.Series

In [79]:
type(df)

pandas.DataFrame

In [16]:
df.price
# xem cột price hoặc dùng  => df['price]

0      13495
1      16500
2      16500
3      13950
4      17450
       ...
200    16845
201    19045
202    21485
203    22470
204    22625
Name: price, Length: 205, dtype: str

In [81]:
df[['highway-mpg', 'engine-size', 'price']]
# lấy nhiều cột

     highway-mpg  engine-size  price
0             27          130  13495
1             27          130  16500
2             26          152  16500
3             30          109  13950
4             22          136  17450
..           ...          ...    ...
200           28          141  16845
201           25          141  19045
202           23          173  21485
203           27          145  22470
204           25          141  22625

[205 rows x 3 columns]

In [18]:
df.select_dtypes(include='number')
# chỉ lấy các cột có kiểu dữ liệu là number (số), bỏ các kiểu dữ liệu khác như oject, ?,....

,symboling,wheel-base,length,width,height,curb-weight,engine-size,compression-ratio,city-mpg,highway-mpg
0,3,88.6,168.8,64.1,48.8,2548,130,9.0,21,27
1,3,88.6,168.8,64.1,48.8,2548,130,9.0,21,27
2,1,94.5,171.2,65.5,52.4,2823,152,9.0,19,26
3,2,99.8,176.6,66.2,54.3,2337,109,10.0,24,30
4,2,99.4,176.6,66.4,54.3,2824,136,8.0,18,22
...,...,...,...,...,...,...,...,...,...,...
200,-1,109.1,188.8,68.9,55.5,2952,141,9.5,23,28
201,-1,109.1,188.8,68.8,55.5,3049,141,8.7,19,25
202,-1,109.1,188.8,68.9,55.5,3012,173,8.8,18,23
203,-1,109.1,188.8,68.9,55.5,3217,145,23.0,26,27
204,-1,109.1,188.8,68.9,55.5,3062,141,9.5,19,25

In [86]:
df.info()
#info dùng để xem biết số dòng số cột và biết kiểu dữ liệu của nó là gì
#=> mục đích là phát hiện cột nào sai kiểu dữ liệu
# số + chuỗi =object
# phiên bản mới => sẽ ra string ko phải object

<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    str
 2   make               205 non-null    str
 3   fuel-type          205 non-null    str
 4   aspiration         205 non-null    str
 5   num-of-doors       205 non-null    str
 6   body-style         205 non-null    str
 7   drive-wheels       205 non-null    str
 8   engine-location    205 non-null    str
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    str
 15  num-of-cylinders   205 non-null    str
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    str
 18  bore               205 non-null    str
 19  stroke             205 non-null    str
 20  compression-ratio  205 non-null    float64
 21  horsepower         205 non-null    str
 22  peak-rpm           205 non-null    str
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              205 non-null    str
dtypes: float64(5), int64(5), str(16)
memory usage: 41.8 KB

In [87]:
df.head() #hiển thị bao nhiêu dòng đầu

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [88]:
df.tail(10) # hiển thị cuối

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
195,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,13415
196,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,15985
197,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,16515
198,-2,103,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18420
199,-1,74,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18950
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [29]:
# df.sample(10)
#random mẫu bất kì

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
76,2,161,mitsubishi,gas,std,two,hatchback,fwd,front,93.7,...,92,2bbl,2.97,3.23,9.4,68,5500,37,41,5389
105,3,194,nissan,gas,turbo,two,hatchback,rwd,front,91.3,...,181,mpfi,3.43,3.27,7.8,200,5200,17,23,19699
62,0,115,mazda,gas,std,four,sedan,fwd,front,98.8,...,122,2bbl,3.39,3.39,8.6,84,4800,26,32,10245
147,0,89,subaru,gas,std,four,wagon,fwd,front,97.0,...,108,mpfi,3.62,2.64,9.0,94,5200,25,31,10198
192,0,?,volkswagen,diesel,turbo,four,sedan,fwd,front,100.4,...,97,idi,3.01,3.40,23.0,68,4500,33,38,13845
154,0,81,toyota,gas,std,four,wagon,4wd,front,95.7,...,92,2bbl,3.05,3.03,9.0,62,4800,27,32,7898
175,-1,65,toyota,gas,std,four,hatchback,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.7,92,4200,27,32,9988
61,1,129,mazda,gas,std,two,hatchback,fwd,front,98.8,...,122,2bbl,3.39,3.39,8.6,84,4800,26,32,10595
42,1,107,honda,gas,std,two,sedan,fwd,front,96.5,...,110,2bbl,3.15,3.58,9.1,100,5500,25,31,10345
177,-1,65,toyota,gas,std,four,hatchback,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.7,92,4200,27,32,11248

In [19]:
df.shape
# bao nhiêu hàng bao nhiêu cột

(205, 26)

In [68]:
df2=df.sample(10)

In [74]:
# df2.to_csv('../dataset/dataset_bai01_createNew.csv')
""""
Pandas sẽ lưu DataFrame df2 thành một file CSV mới có tên là dataset_bai01_createNew.csv
=> ta sẽ có 2 file dataset: 1 gốc, 1 file mới tạo
"""

In [20]:
#dtype kiểm tra các cột (series) có kiểu dữ liệu gì? -> oject,string,..
s= pd.Series(data=[2,6,7,9,'?'])
s.dtypes

# in ra dtype('O') => O trong Object
""""
Vì có cả số ( 2,6,7,9)  và chuỗi ('?'), Pandas không thể để kiểu dữ liệu là int,
nên nó chuyển toàn bộ Series sang Object

Oject là kiểu dữ liệu tổng quát, chứa nhiều kiểu dữ liệu khác nhau hoặc chứa chuỗi
"""

dtype('O')

In [ ]:
# 0   symboling          int64
# 1   normalized-losses  str         => int64
# 2   make               str
# 3   fuel-type          str
# 4   aspiration         str
# 5   num-of-doors       str
# 6   body-style         str
# 7   drive-wheels       str
# 8   engine-location    str
# 9   wheel-base         float64
# 10  length             float64
# 11  width              float64
# 12  height             float64
# 13  curb-weight        int64
# 14  engine-type        str
# 15  num-of-cylinders   str
# 16  engine-size        int64
# 17  fuel-system        str
# 18  bore               str         => float64
# 19  stroke             str        => float64
# 20  compression-ratio  float64
# 21  horsepower         str         => int
# 22  peak-rpm           str         => int
# 23  city-mpg           int64
# 24  highway-mpg        int64
# 25  price              str         => int

In [2]:
import  numpy as np


# quy ước khuyết => dấu ? ko nhận
# chỉ nhận gi trị NAN
np.nan

In [ ]:
pd.NA

In [18]:
df =pd.DataFrame(data={
    'a':[2,5, np.nan, 5, 8],
    'b':[2,5, np.nan, 5, 8],
    'c':['?',5, np.nan, 5, 8] }
)

df

     a    b    c
0  2.0  2.0    ?
1  5.0  5.0    5
2  NaN  NaN  NaN
3  5.0  5.0    5
4  8.0  8.0    8

In [19]:
# axis =0: xóa dòng , axis=1: xóa cột
#loại bỏ giá trị NAN, ko loại bỏ dc '?'
df.dropna(axis=0, subset=['a'])
# chọn dòng xóa cột a

     a    b  c
0  2.0  2.0  ?
1  5.0  5.0  5
3  5.0  5.0  5
4  8.0  8.0  8

In [ ]:
#inplace lưu giá trị thay đổi vào df
df.dropna(axis=0, subset=['a'], inplace=True)

In [21]:
df.replace(to_replace="?", value=np.nan, inplace=True)

     a    b    c
0  2.0  2.0  NaN
1  5.0  5.0    5
2  NaN  NaN  NaN
3  5.0  5.0    5
4  8.0  8.0    8

In [22]:
df

     a    b    c
0  2.0  2.0  NaN
1  5.0  5.0    5
2  NaN  NaN  NaN
3  5.0  5.0    5
4  8.0  8.0    8

In [35]:
import pandas as pd
df=pd.read_csv('../dataset/dataset_bai02.csv', names=[
"symboling",
"normalized-losses",
"make",
"fuel-type",
"aspiration",
"num-of-doors",
"body-style",
"drive-wheels",
"engine-location",
"wheel-base",
"length",
"width",
"height",
"curb-weight",
"engine-type",
"num-of-cylinders",
"engine-size",
"fuel-system",
"bore","stroke",
"compression-ratio",
"horsepower",
"peak-rpm",
"city-mpg",
"highway-mpg",
"price"])

In [50]:
df.to_csv('../dataset/dataset_bai03.csv', index=False)

In [59]:
df.head(5)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [60]:
df.replace(to_replace='?', value=np.nan, inplace=True)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [61]:
df.dropna()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [56]:
s = pd.Series(data=[2,2,5,7,2,5])
s.mode()
# hiển thị số nào xuất hiện nhiều nhất

0    2
dtype: int64

In [62]:
df['L/100km_city']= 235/df['city-mpg']
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,L/100km_city
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000,21,27,13495,11.190476
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,mpfi,3.47,2.68,9.0,111,5000,21,27,16500,11.190476
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,mpfi,2.68,3.47,9.0,154,5000,19,26,16500,12.368421
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,mpfi,3.19,3.40,10.0,102,5500,24,30,13950,9.791667
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,mpfi,3.19,3.40,8.0,115,5500,18,22,17450,13.055556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,mpfi,3.78,3.15,9.5,114,5400,23,28,16845,10.217391
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,mpfi,3.78,3.15,8.7,160,5300,19,25,19045,12.368421
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,mpfi,3.58,2.87,8.8,134,5500,18,23,21485,13.055556
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,idi,3.01,3.40,23.0,106,4800,26,27,22470,9.038462
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,mpfi,3.78,3.15,9.5,114,5400,19,25,22625,12.368421

In [77]:
from sklearn.preprocessing import MinMaxScaler

In [78]:
df['length'] = (df['length'] - df['length'].min()) / (df['length'].max() - df['length'].min())

In [79]:
mm=MinMaxScaler()

In [86]:
mm.fit_transform(df[['length']])

array([[0.41343284],
       [0.41343284],
       [0.44925373],
       [0.52985075],
       [0.52985075],
       [0.54029851],
       [0.77014925],
       [0.77014925],
       [0.77014925],
       [0.55373134],
       [0.53283582],
       [0.53283582],
       [0.53283582],
       [0.53283582],
       [0.71492537],
       [0.71492537],
       [0.78656716],
       [0.83432836],
       [0.        ],
       [0.22089552],
       [0.2641791 ],
       [0.24179104],
       [0.24179104],
       [0.24179104],
       [0.24179104],
       [0.24179104],
       [0.24179104],
       [0.24179104],
       [0.5       ],
       [0.47910448],
       [0.05223881],
       [0.05223881],
       [0.13283582],
       [0.13283582],
       [0.13283582],
       [0.33283582],
       [0.23880597],
       [0.39402985],
       [0.39402985],
       [0.5119403 ],
       [0.5119403 ],
       [0.5119403 ],
       [0.41791045],
       [0.44179104],
       [0.22089552],
       [0.22089552],
       [0.47014925],
       [0.87313433],
       [0.87313433],
       [0.75522388],
       [0.26865672],
       [0.26865672],
       [0.26865672],
       [0.38358209],
       [0.38358209],
       [0.41641791],
       [0.41641791],
       [0.41641791],
       [0.41641791],
       [0.54776119],
       [0.54776119],
       [0.54776119],
       [0.54776119],
       [0.54776119],
       [0.54776119],
       [0.50597015],
       [0.50597015],
       [0.74328358],
       [0.74328358],
       [0.69253731],
       [0.91791045],
       [0.91791045],
       [0.58507463],
       [1.        ],
       [0.86716418],
       [0.55671642],
       [0.24179104],
       [0.24179104],
       [0.24179104],
       [0.24179104],
       [0.4761194 ],
       [0.4761194 ],
       [0.47910448],
       [0.47910448],
       [0.47910448],
       [0.46716418],
       [0.46716418],
       [0.46716418],
       [0.46716418],
       [0.36119403],
       [0.36119403],
       [0.36119403],
       [0.36119403],
       [0.43432836],
       [0.36119403],
       [0.36567164],
       [0.36119403],
       [0.43432836],
       [0.31791045],
       [0.48208955],
       [0.48208955],
       [0.60597015],
       [0.64925373],
       [0.64925373],
       [0.44179104],
       [0.44179104],
       [0.55820896],
       [0.68059701],
       [0.68059701],
       [0.86268657],
       [0.86268657],
       [0.68059701],
       [0.68059701],
       [0.86268657],
       [0.86268657],
       [0.68059701],
       [0.68059701],
       [0.68059701],
       [0.24179104],
       [0.24179104],
       [0.24179104],
       [0.39104478],
       [0.39104478],
       [0.5       ],
       [0.47910448],
       [0.41492537],
       [0.41492537],
       [0.41492537],
       [0.41492537],
       [0.51641791],
       [0.60298507],
       [0.53283582],
       [0.67910448],
       [0.67910448],
       [0.67910448],
       [0.67910448],
       [0.67910448],
       [0.67910448],
       [0.2358209 ],
       [0.25074627],
       [0.24179104],
       [0.46119403],
       [0.46119403],
       [0.46119403],
       [0.46119403],
       [0.46119403],
       [0.48358209],
       [0.48358209],
       [0.48507463],
       [0.48507463],
       [0.26268657],
       [0.26268657],
       [0.26268657],
       [0.42686567],
       [0.42686567],
       [0.42686567],
       [0.3761194 ],
       [0.3761194 ],
       [0.3761194 ],
       [0.3761194 ],
       [0.3761194 ],
       [0.3761194 ],
       [0.3761194 ],
       [0.4119403 ],
       [0.4119403 ],
       [0.4119403 ],
       [0.4119403 ],
       [0.5238806 ],
       [0.5238806 ],
       [0.5238806 ],
       [0.5238806 ],
       [0.5238806 ],
       [0.5238806 ],
       [0.51492537],
       [0.51492537],
       [0.51492537],
       [0.51492537],
       [0.51492537],
       [0.63283582],
       [0.63283582],
       [0.69701493],
       [0.69701493],
       [0.45671642],
       [0.45671642],
       [0.45671642],
       [0.45671642],
       [0.45671642],
       [0.45671642],
       [0.45671642],
       [0.27164179],
       [0.36716418],
       [0.58358209],
       [0.58358209],
       [0.62686567],
       [0.7119403 ],
       [0.7119403 ],
       [0.7119403 ],
       [0.7119403 ],
       [0.7119403 ],
       [0.7119403 ],
       [0.7119403 ],
       [0.7119403 ],
       [0.7119403 ],
       [0.7119403 ],
       [0.7119403 ]])