In [12]:
import pandas as pd
import numpy as np

df = pd.read_csv('../dataset/dataset_bai03.csv')
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [14]:
df.replace(to_replace="?", value=np.nan, inplace=True)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [17]:
# dropna trên cột 'price'
df.dropna( inplace=True)

In [18]:
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [37]:
numeric_cols = [
    'normalized-losses',
    'bore',
    'stroke',
    'horsepower',
    'peak-rpm',
    'price'
]

In [38]:
df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric)

In [39]:
df1 = df.copy()

In [40]:
make_mapping = {
    make: i
    for i, make in enumerate(df1['make'].unique())
}

df1['make'] = df1['make'].map(make_mapping)

In [41]:
make_mapping

{'audi': 0,
 'bmw': 1,
 'chevrolet': 2,
 'dodge': 3,
 'honda': 4,
 'jaguar': 5,
 'mazda': 6,
 'mercedes-benz': 7,
 'mitsubishi': 8,
 'nissan': 9,
 'peugot': 10,
 'plymouth': 11,
 'porsche': 12,
 'saab': 13,
 'subaru': 14,
 'toyota': 15,
 'volkswagen': 16,
 'volvo': 17}

In [47]:
df1['num-of-doors'] = df1['num-of-doors'].replace({
    'two': 1,
    'four': 2
}).astype(int)

In [48]:
df1['num-of-doors']

3      2
4      2
6      2
8      2
10     1
      ..
200    2
201    2
202    2
203    2
204    2
Name: num-of-doors, Length: 159, dtype: int64

In [50]:
df2 = df1.copy()

In [51]:
df2.select_dtypes(include='str').columns

Index(['fuel-type', 'aspiration', 'body-style', 'drive-wheels',
       'engine-location', 'engine-type', 'num-of-cylinders', 'fuel-system'],
      dtype='str')

In [52]:
df2 = pd.get_dummies(df2, dtype=int)

In [53]:
df2

,symboling,normalized-losses,make,num-of-doors,wheel-base,length,width,height,curb-weight,engine-size,...,num-of-cylinders_five,num-of-cylinders_four,num-of-cylinders_six,num-of-cylinders_three,fuel-system_1bbl,fuel-system_2bbl,fuel-system_idi,fuel-system_mfi,fuel-system_mpfi,fuel-system_spdi
3,2,164,0,2,99.8,176.6,66.2,54.3,2337,109,...,0,1,0,0,0,0,0,0,1,0
4,2,164,0,2,99.4,176.6,66.4,54.3,2824,136,...,1,0,0,0,0,0,0,0,1,0
6,1,158,0,2,105.8,192.7,71.4,55.7,2844,136,...,1,0,0,0,0,0,0,0,1,0
8,1,158,0,2,105.8,192.7,71.4,55.9,3086,131,...,1,0,0,0,0,0,0,0,1,0
10,2,192,1,1,101.2,176.8,64.8,54.3,2395,108,...,0,1,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,17,2,109.1,188.8,68.9,55.5,2952,141,...,0,1,0,0,0,0,0,0,1,0
201,-1,95,17,2,109.1,188.8,68.8,55.5,3049,141,...,0,1,0,0,0,0,0,0,1,0
202,-1,95,17,2,109.1,188.8,68.9,55.5,3012,173,...,0,0,1,0,0,0,0,0,1,0
203,-1,95,17,2,109.1,188.8,68.9,55.5,3217,145,...,0,0,1,0,0,0,1,0,0,0
204,-1,95,17,2,109.1,188.8,68.9,55.5,3062,141,...,0,1,0,0,0,0,0,0,1,0

In [54]:
df3 = df2.copy()

In [55]:
df3 = (df3 - df3.mean()) / df3.std()

In [56]:
df3

,symboling,normalized-losses,make,num-of-doors,wheel-base,length,width,height,curb-weight,engine-size,...,num-of-cylinders_five,num-of-cylinders_four,num-of-cylinders_six,num-of-cylinders_three,fuel-system_1bbl,fuel-system_2bbl,fuel-system_idi,fuel-system_mfi,fuel-system_mpfi,fuel-system_spdi
3,1.059564,1.202423,-2.026245,0.818198,0.297218,0.363282,0.304152,0.176585,-0.257580,-0.335724,...,-0.213923,0.409944,-0.309749,-0.079305,-0.271766,-0.807541,-0.321732,-0.079305,1.214512,-0.17962
4,1.059564,1.202423,-2.026245,0.818198,0.219810,0.363282,0.406828,0.176585,0.752917,0.550661,...,4.645182,-2.424016,-0.309749,-0.079305,-0.271766,-0.807541,-0.321732,-0.079305,1.214512,-0.17962
6,0.221401,1.034126,-2.026245,0.818198,1.458340,1.760466,2.973718,0.793662,0.794415,0.550661,...,4.645182,-2.424016,-0.309749,-0.079305,-0.271766,-0.807541,-0.321732,-0.079305,1.214512,-0.17962
8,0.221401,1.034126,-2.026245,0.818198,1.458340,1.760466,2.973718,0.881816,1.296551,0.386516,...,4.645182,-2.424016,-0.309749,-0.079305,-0.271766,-0.807541,-0.321732,-0.079305,1.214512,-0.17962
10,1.059564,1.987808,-1.825889,-1.214512,0.568146,0.380638,-0.414577,0.176585,-0.137233,-0.368553,...,-0.213923,0.409944,-0.309749,-0.079305,-0.271766,-0.807541,-0.321732,-0.079305,1.214512,-0.17962
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1.454924,-0.732991,1.379813,0.818198,2.096957,1.422018,1.690273,0.705508,1.018509,0.714807,...,-0.213923,0.409944,-0.309749,-0.079305,-0.271766,-0.807541,-0.321732,-0.079305,1.214512,-0.17962
201,-1.454924,-0.732991,1.379813,0.818198,2.096957,1.422018,1.638935,0.705508,1.219778,0.714807,...,-0.213923,0.409944,-0.309749,-0.079305,-0.271766,-0.807541,-0.321732,-0.079305,1.214512,-0.17962
202,-1.454924,-0.732991,1.379813,0.818198,2.096957,1.422018,1.690273,0.705508,1.143006,1.765338,...,-0.213923,-2.424016,3.208115,-0.079305,-0.271766,-0.807541,-0.321732,-0.079305,1.214512,-0.17962
203,-1.454924,-0.732991,1.379813,0.818198,2.096957,1.422018,1.690273,0.705508,1.568369,0.846123,...,-0.213923,-2.424016,3.208115,-0.079305,-0.271766,-0.807541,3.088628,-0.079305,-0.818198,-0.17962
204,-1.454924,-0.732991,1.379813,0.818198,2.096957,1.422018,1.690273,0.705508,1.246753,0.714807,...,-0.213923,0.409944,-0.309749,-0.079305,-0.271766,-0.807541,-0.321732,-0.079305,1.214512,-0.17962