In [35]:
import pandas as pd
import numpy as np
df=pd.read_csv('../dataset/dataset_bai03.csv')
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [36]:
# Chuyển '?' thành NaN để dropna nhận dạng được
df.replace(to_replace="?", value=np.nan, inplace=True)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [4]:
# dropna trên cột 'price'
df.dropna( axis=0,subset=["price"], inplace=True)
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [5]:
#Xử lý cột horsepower - Replace bằng mean
mean_horsepower = df["horsepower"].astype(float).mean()

In [12]:
df["horsepower"] = df["horsepower"].replace( to_replace=np.nan,value=mean_horsepower)

In [22]:
df["normalized-losses"] = df["normalized-losses"].astype(float)

In [23]:
mode_losses = df["normalized-losses"].mode()[0]

In [26]:
df["normalized-losses"] = df["normalized-losses"].replace(to_replace=np.nan, value=mode_losses)

In [37]:
df.dropna(inplace=True)
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [28]:
print(df.dtypes) # kiểm tra kiểu dữ liệu

symboling              int64
normalized-losses    float64
make                     str
fuel-type                str
aspiration               str
num-of-doors             str
body-style               str
drive-wheels             str
engine-location          str
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type              str
num-of-cylinders         str
engine-size            int64
fuel-system              str
bore                     str
stroke                   str
compression-ratio    float64
horsepower            object
peak-rpm                 str
city-mpg               int64
highway-mpg            int64
price                    str
dtype: object

In [29]:
df["price"] = df["price"].astype(int)

df["horsepower"] = df["horsepower"].astype(float)

df["normalized-losses"] = df["normalized-losses"].astype(int)

df["bore"] = df["bore"].astype(float)

df["stroke"] = df["stroke"].astype(float)

df["peak-rpm"] = df["peak-rpm"].astype(float)

In [30]:
# Min-Max bằng công thức

df["length_minmax"] = (
    (df["length"] - df["length"].min()) /
    (df["length"].max() - df["length"].min())
)

df["width_minmax"] = (
    (df["width"] - df["width"].min()) /
    (df["width"].max() - df["width"].min())
)

df["height_minmax"] = (
    (df["height"] - df["height"].min()) /
    (df["height"].max() - df["height"].min())
)

df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price,length_minmax,width_minmax,height_minmax
0,3,161,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,2.68,9.0,111.0,5000.0,21,27,13495,0.413433,0.324786,0.083333
1,3,161,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,2.68,9.0,111.0,5000.0,21,27,16500,0.413433,0.324786,0.083333
2,1,161,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,3.47,9.0,154.0,5000.0,19,26,16500,0.449254,0.444444,0.383333
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,3.40,10.0,102.0,5500.0,24,30,13950,0.529851,0.504274,0.541667
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,3.40,8.0,115.0,5500.0,18,22,17450,0.529851,0.521368,0.541667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,3.15,9.5,114.0,5400.0,23,28,16845,0.711940,0.735043,0.641667
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,3.15,8.7,160.0,5300.0,19,25,19045,0.711940,0.726496,0.641667
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,2.87,8.8,134.0,5500.0,18,23,21485,0.711940,0.735043,0.641667
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,3.40,23.0,106.0,4800.0,26,27,22470,0.711940,0.735043,0.641667
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,3.15,9.5,114.0,5400.0,19,25,22625,0.711940,0.735043,0.641667

In [31]:
#min max Theo thư viện
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df[["length_MinMaxScaler",
    "width_MinMaxScaler",
    "height_MinMaxScaler"]] = scaler.fit_transform(
    df[["length", "width", "height"]]
)
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,peak-rpm,city-mpg,highway-mpg,price,length_minmax,width_minmax,height_minmax,length_MinMaxScaler,width_MinMaxScaler,height_MinMaxScaler
0,3,161,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,5000.0,21,27,13495,0.413433,0.324786,0.083333,0.413433,0.324786,0.083333
1,3,161,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,5000.0,21,27,16500,0.413433,0.324786,0.083333,0.413433,0.324786,0.083333
2,1,161,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,5000.0,19,26,16500,0.449254,0.444444,0.383333,0.449254,0.444444,0.383333
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,5500.0,24,30,13950,0.529851,0.504274,0.541667,0.529851,0.504274,0.541667
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,5500.0,18,22,17450,0.529851,0.521368,0.541667,0.529851,0.521368,0.541667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,5400.0,23,28,16845,0.711940,0.735043,0.641667,0.711940,0.735043,0.641667
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,5300.0,19,25,19045,0.711940,0.726496,0.641667,0.711940,0.726496,0.641667
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,5500.0,18,23,21485,0.711940,0.735043,0.641667,0.711940,0.735043,0.641667
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,4800.0,26,27,22470,0.711940,0.735043,0.641667,0.711940,0.735043,0.641667
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,5400.0,19,25,22625,0.711940,0.735043,0.641667,0.711940,0.735043,0.641667

In [69]:
# Scale công thức

df["length_scale"] = df["length"] / df["length"].max()
df["width_scale"] = df["width"] / df["width"].max()
df["height_scale"] = df["height"] / df["height"].max()

df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,price,length_minmax,width_minmax,height_minmax,length_MinMaxScaler,width_MinMaxScaler,height_MinMaxScaler,length_scale,width_scale,height_scale
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,13950,0.577236,0.517544,0.471154,0.577236,0.517544,0.471154,0.871668,0.923291,0.908027
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,17450,0.577236,0.535088,0.471154,0.577236,0.535088,0.471154,0.871668,0.926081,0.908027
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,17710,0.839024,0.973684,0.605769,0.839024,0.973684,0.605769,0.951135,0.995816,0.931438
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,23875,0.839024,0.973684,0.625000,0.839024,0.973684,0.625000,0.951135,0.995816,0.934783
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,16430,0.580488,0.394737,0.471154,0.580488,0.394737,0.471154,0.872655,0.903766,0.908027
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,16845,0.775610,0.754386,0.586538,0.775610,0.754386,0.586538,0.931885,0.960948,0.928094
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,19045,0.775610,0.745614,0.586538,0.775610,0.745614,0.586538,0.931885,0.959554,0.928094
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,21485,0.775610,0.754386,0.586538,0.775610,0.754386,0.586538,0.931885,0.960948,0.928094
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,22470,0.775610,0.754386,0.586538,0.775610,0.754386,0.586538,0.931885,0.960948,0.928094
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,22625,0.775610,0.754386,0.586538,0.775610,0.754386,0.586538,0.931885,0.960948,0.928094

In [32]:
# scale theo thư viện

from sklearn.preprocessing import MaxAbsScaler

scaler = MaxAbsScaler()

df[["length_MaxAbsScaler",
    "width_MaxAbsScaler",
    "height_MaxAbsScaler"]] = scaler.fit_transform(
    df[["length", "width", "height"]]
)
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,price,length_minmax,width_minmax,height_minmax,length_MinMaxScaler,width_MinMaxScaler,height_MinMaxScaler,length_MaxAbsScaler,width_MaxAbsScaler,height_MaxAbsScaler
0,3,161,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,13495,0.413433,0.324786,0.083333,0.413433,0.324786,0.083333,0.811148,0.890278,0.816054
1,3,161,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,16500,0.413433,0.324786,0.083333,0.413433,0.324786,0.083333,0.811148,0.890278,0.816054
2,1,161,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,16500,0.449254,0.444444,0.383333,0.449254,0.444444,0.383333,0.822681,0.909722,0.876254
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,13950,0.529851,0.504274,0.541667,0.529851,0.504274,0.541667,0.848630,0.919444,0.908027
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,17450,0.529851,0.521368,0.541667,0.529851,0.521368,0.541667,0.848630,0.922222,0.908027
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,16845,0.711940,0.735043,0.641667,0.711940,0.735043,0.641667,0.907256,0.956944,0.928094
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,19045,0.711940,0.726496,0.641667,0.711940,0.726496,0.641667,0.907256,0.955556,0.928094
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,21485,0.711940,0.735043,0.641667,0.711940,0.735043,0.641667,0.907256,0.956944,0.928094
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,22470,0.711940,0.735043,0.641667,0.711940,0.735043,0.641667,0.907256,0.956944,0.928094
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,22625,0.711940,0.735043,0.641667,0.711940,0.735043,0.641667,0.907256,0.956944,0.928094

In [33]:
# Z score theo thư viện
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

df[["length_StandardScaler",
    "width_StandardScaler",
    "height_StandardScaler"]] = scaler.fit_transform(
    df[["length", "width", "height"]]
)
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,height_minmax,length_MinMaxScaler,width_MinMaxScaler,height_MinMaxScaler,length_MaxAbsScaler,width_MaxAbsScaler,height_MaxAbsScaler,length_StandardScaler,width_StandardScaler,height_StandardScaler
0,3,161,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,0.083333,0.413433,0.324786,0.083333,0.811148,0.890278,0.816054,-0.444024,-0.841263,-2.122598
1,3,161,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,0.083333,0.413433,0.324786,0.083333,0.811148,0.890278,0.816054,-0.444024,-0.841263,-2.122598
2,1,161,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,0.383333,0.449254,0.444444,0.383333,0.822681,0.909722,0.876254,-0.251195,-0.184679,-0.615412
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,0.541667,0.529851,0.504274,0.541667,0.848630,0.919444,0.908027,0.182672,0.143612,0.180047
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,0.541667,0.529851,0.521368,0.541667,0.848630,0.922222,0.908027,0.182672,0.237410,0.180047
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,0.641667,0.711940,0.735043,0.641667,0.907256,0.956944,0.928094,1.162889,1.409880,0.682442
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,0.641667,0.711940,0.726496,0.641667,0.907256,0.955556,0.928094,1.162889,1.362982,0.682442
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,0.641667,0.711940,0.735043,0.641667,0.907256,0.956944,0.928094,1.162889,1.409880,0.682442
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,0.641667,0.711940,0.735043,0.641667,0.907256,0.956944,0.928094,1.162889,1.409880,0.682442
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,0.641667,0.711940,0.735043,0.641667,0.907256,0.956944,0.928094,1.162889,1.409880,0.682442

In [34]:
# Z-score bằng công thức

df["length_zscore"] = (
    (df["length"] - df["length"].mean()) /
    df["length"].std()
)

df["width_zscore"] = (
    (df["width"] - df["width"].mean()) /
    df["width"].std()
)

df["height_zscore"] = (
    (df["height"] - df["height"].mean()) /
    df["height"].std()
)
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,height_MinMaxScaler,length_MaxAbsScaler,width_MaxAbsScaler,height_MaxAbsScaler,length_StandardScaler,width_StandardScaler,height_StandardScaler,length_zscore,width_zscore,height_zscore
0,3,161,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,0.083333,0.811148,0.890278,0.816054,-0.444024,-0.841263,-2.122598,-0.442872,-0.839080,-2.117092
1,3,161,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,0.083333,0.811148,0.890278,0.816054,-0.444024,-0.841263,-2.122598,-0.442872,-0.839080,-2.117092
2,1,161,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,0.383333,0.822681,0.909722,0.876254,-0.251195,-0.184679,-0.615412,-0.250543,-0.184200,-0.613816
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,0.541667,0.848630,0.919444,0.908027,0.182672,0.143612,0.180047,0.182198,0.143240,0.179580
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,0.541667,0.848630,0.922222,0.908027,0.182672,0.237410,0.180047,0.182198,0.236794,0.179580
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,0.641667,0.907256,0.956944,0.928094,1.162889,1.409880,0.682442,1.159872,1.406223,0.680671
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,0.641667,0.907256,0.955556,0.928094,1.162889,1.362982,0.682442,1.159872,1.359446,0.680671
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,0.641667,0.907256,0.956944,0.928094,1.162889,1.409880,0.682442,1.159872,1.406223,0.680671
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,0.641667,0.907256,0.956944,0.928094,1.162889,1.409880,0.682442,1.159872,1.406223,0.680671
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,0.641667,0.907256,0.956944,0.928094,1.162889,1.409880,0.682442,1.159872,1.406223,0.680671

# 3.chuyển giá trị số thành các giá trị phân loại